customhost = "database-1.cnbrumjk0t55.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "angguoliang-employee"
customregion = "us-east-1"
